<!doctype html>
<!--[if lt IE 7 ]> <html class=ie6> <![endif]-->
<!--[if IE 7 ]> <html class=ie7> <![endif]-->
<!--[if IE 8 ]> <html class=ie8> <![endif]-->
<!--[if IE 9 ]> <html class=ie9> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
<head>
<!--[if lt IE 9]>l
<script src=http://html5shiv.googlecode.com/svn/trunk/html5.js></script>
<![endif]-->
<meta charset="utf-8">
<title>Mars Petrochem Pvt Ltd | Marine Lubricants</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="rating" content="general" />
<meta name="copyright" content="2014, mars petrochem" />
<meta name="revisit-after" content="7 Days" />
<meta name="expires" content="never" />
<meta name="distribution" content="global" />
<meta name="robots" content="index, follow" />
<!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<meta name="viewport" content="width=1240px">
<link type="text/css" rel="stylesheet" href="css/main.css" />
<link rel="icon" href="images/favicon.ico"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>


<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
        <script type="text/javascript" src="js/ticker.js"></script>
<!-- End WOWSlider.com HEAD section -->
<link rel="stylesheet" href="css/accordian.css" />
<script type="text/javascript" src="js/accordian.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>

<body>
<div class="float header-bg">
<div class="auto2">
<div class="auto">
<div class="float">

<ul class="menu">
<li ><a href="index.php">HOME</a></li>
<li><a href="about-us.php#about-us">PROFILE</a>
 <ul class="dropmenu">
  <li><a href="about-us.php#about-us">About Us</a></li>
  <li><a href="our-mission.php#our-mission">Our Mission</a></li>
  <li><a href="our-vision.php#our-vision">Our Vision</a></li>
  <li><a href="our-people.php#our-people">Our People</a></li>
  <li><a href="Infrastructure.php#Infrastructure">Infrastructure</a></li>
  <li><a href="awards-and-accolades.php#awards">Awards and Accolades</a></li>
  </ul>
</li>
<li class="active"><a href="industrial-lubricants.php#industrial-lubricantss">PRODUCT</a>
	<ul class="dropmenu">
      <li><a href="industrial-lubricants.php#industrial-lubricants">Industrial Lubricants</a></li>
      <li><a href="automotive-lubricants.php#automotive-lubricant">Automotive Lubricants</a></li>
      <li><a href="marine-lubricants.php#marine-lubricants">Marine Lubricants</a></li>
  </ul>
</li>
<li><a href="gallery.php#gallery">GALLERY</a></li>
<li><a href="careers.php#careers">CAREERS</a></li>
<li ><a href="contact-us.php#contact-us">CONTACT</a></li>
<li><a href="events.php#events">EVENTS</a></li>
<li><a href="partners.php#partners">PARTNERS</a></li>
</ul>

<div class="right">
<ul class="links">
<li><a href="http://www.mobilindustrial.com/ind/english/productselector.aspx" target="_blank"><img src="images/blue-btn1-bg.png" width="205px" alt="product selector" title="Product Selector" /></a></li>
<li><a href="http://www.msds.exxonmobil.com/IntApps/psims/psims.aspx" target="_blank"><img src="images/blue-btn2-bg.png" width="150px" alt="Material Safety Data Sheet" title="Material Safety Data Sheet" /></a></li>
</ul>
</div>



<div class="float">
<div class="left mt30">
<a href="index.php"><img src="images/logo.png" alt="logo" title="logo" /></a>
</div>
<div class="left mt50 ml40">
<img src="images/mobil-logo.png" alt="mobil" title="mobil" />
</div>

<div class="right mt25 phone">
<h6><img src="images/icon-1.png" alt="phone" title="phone"/>+91-22-65505615/07/08/+91-22-23723836</h6>
<h6><img src="images/icon-2.png" alt="email" title="email" /><a style="color:#333333;" href="mailto:info@marspetrochem.com">info@marspetrochem.com</a></h6>
</div>
</div>


</div>
</div>
</div>
</div>







<div class="float relative">
<div class="absolute">
<img src="images/awards.png" alt="awards" title="awards" />
</div>

<!-- Start WOWSlider.com BODY section id=wowslider-container1 -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/img1.jpg" alt="img1" title="img1" id="wows1_0"/></li>
<li><img src="data1/images/img4.jpg" alt="img4" title="img4" id="wows1_1"/></li>
<li><img src="data1/images/img1.jpg" alt="img1" title="img3" id="wows1_2"/></li>
<li><img src="data1/images/img4.jpg" alt="img4" title="img1" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="img1">1</a>
<a href="#" title="img4">2</a>
<a href="#" title="img1">3</a>
<a href="#" title="img4">4</a>
</div></div>
<!-- Generated by WOWSlider.com v3.4 -->
	<a href="#" class="ws_frame"></a>
	
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
<!-- End WOWSlider.com BODY section -->

</div>

<div class="float">
<div class="auto">
<div class="auto2">
<div class="float">
<ul class="clients">
<li><img src="images/icon-4.png" /></li>
<li><img src="images/client-1.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-2.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-3.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-4.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-5.png" /></li>
</ul>
</div>
</div>
</div>
</div>

<div id="marine-lubricants" class="float dark-green">
<div class="auto2">
<div class="auto">
<div class="float">
<div class="left mt15 mb5">
<img src="images/icon-3.png" alt="news"  title="news" />
</div>
<div class="float mt15 ml30" id="ticker">
<ul>
    <li><h5>Gulf Oil Lubri standalone Sep '14 sales at Rs 243.27 crore</h5>
    <span class="left">5.13 pm | 06 Nov 2014 |  Source: <a href="http://www.moneycontrol.com/">Moneycontrol.com</a></span>

    </li>
    <li><h5>Gulf Oil Lubri standalone Sep '14 sales at Rs 243.27 crore</h5>
    <span class="left">5.13 pm | 06 Nov 2014 |  Source: <a href="http://www.moneycontrol.com/">Moneycontrol.com</a></span>
   
    </li>
 </ul>
<a class="news-btn" href="#">VIEW ALL NEWS</a>
</div>
<script>
$(function() {
  $('#ticker').vTicker();
});
</script>


</div>
</div>
</div>
</div>



<!-- page will come here -->
<div class="float middle-bg ">
<div class="auto2">
<div class="auto">
<div class="float mt30">

<p class="content mb20 font underline"><strong>Marine Lubricants</strong></p>

<div class="float">
<div class="grid2 left">
<img src="images/marine-lubricants.jpg" alt="industrial-lubricant" width="375px" height="240px"/>
</div>
<div class="left grid7">
<p class="content2" style="padding-top:0;"><strong>Marine Lubricants</strong></p>
<p class="content2">
Exxon Mobil Corporation has been serving the lubrication needs of the marine industry since the 1880s. Today, its global lubricants organization – ExxonMobil Marine Lubricants – delivers a complete range of products in nearly 200 countries and territories.

ExxonMobil Marine Lubricants' high-quality products are protecting the engines and shipboard equipment of the world's most important fleets. Our services, such as Signum Oil Analysis, are helping many customers monitor the performance and condition of their fleets' lubricants, engines and shipboard equipment with ease and efficiency. And our team of lubrication professionals is providing expert support, at sea and on land.
</p>
</div>
</div>

<script>
			// Wait until the DOM has loaded before querying the document
			$(document).ready(function(){
				$('ul.tabs2').each(function(){
					// For each set of tabs, we want to keep track of
					// which tab is active and it's associated content
					var $active, $content, $links = $(this).find('a');

					// If the location.hash matches one of the links, use that as the active tab.
					// If no match is found, use the first link as the initial active tab.
					$active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
					$active.addClass('active');

					$content = $($active[0].hash);

					// Hide the remaining content
					$links.not($active).each(function () {
						$(this.hash).hide();
					});

					// Bind the click event handler
					$(this).on('click', 'a', function(e){
						// Make the old tab inactive.
						$active.removeClass('active');
						$content.hide();

						// Update the variables with the new link and content
						$active = $(this);
						$content = $(this.hash);

						// Make the tab active.
						$active.addClass('active');
						$content.show();

						// Prevent the anchor's default click action
						e.preventDefault();
					});
				});
			});
		</script>
<!-- page will come here -->

<div class="float mb40">

<ul class='tabs2'>
<li><a href='#tab1'>Indian Ports</a></li>
<li><a href='#tab2'>Lead Time</a></li>
<li><a href='#tab3'>Ports Rating</a></li>
<li><a href='#tab4'>Port Locator</a></li>
<li><a href="#tab5">Signum Oil Analysis</a></li>
 </ul>
             
    
<div id='tab1' class="tab1">
<div class="container mt30 mb40">
		<div class="float">
			<div class="left grid2">
            	<img src="images/india-map.png"  alt="india-map" width="400px" />
                <ul class="map-sypno">
                	<li><p>Major and Minor Ports of Supply</p></li>
                    <li><p>Stock Points</p></li>
                    <li><p>Blend Plant</p></li>
                </ul>
            </div>
            <div class=" left grid7">
            	<p class="content2"><span><strong class="arrow">  </strong></span>Marine Links has 7 stock points around India coast line in order to supply the key ports in the minimum lead time.<br/><br/>

<span><strong class="arrow"> </strong></span>The blend plant of ExxonMobil is situated at Taloja, Mumbai and is a state of art plant and manufactures all the mineral oil grades of Marine in drum and small pack.<br/><br/>

<span><strong class="arrow">  </strong></span>Marine have supply chains at the ports of Sikka, Kandla, Vapi, Surat, Hazira, Mumbai, Goa, New Mangalore, Cochin, Tuticorin, Ennore, Chennai, Kakinada, Vizag, Paradip, Kolkata, Haldia & Port Blair.<br/><br/>

<span><strong class="arrow">  </strong></span>Marine Links have pumping facility in all ports except Cochin, New Mangalore and Paradip. Pumping to vessels requires prior port authority authorization.</p>
            </div>
         </div>
		</div>
	</div>
	
		<div id='tab2' class="tab1">
			 <div class="container mt30 mb40">
				
                <table class="tg">
                  <tr>
                    <th class="tg-ohfc">SUPPLY WAREHOUSE</th>
                    <th class="tg-med2">LOCATION</th>
                    <th class="tg-med2">LEAD TIME (WORKING DAYS)</th>
                    <th class="tg-med2">SUPPLY POINT RATING</th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mumbai</td>
                    <td class="tg-031e">Kandla</td>
                    <td class="tg-031e">5</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Sikka</td>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Hazira</td>
                    <td class="tg-031e">3</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Murmagoa</td>
                    <td class="tg-031e">3</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Mumbai</td>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Kandala</td>
                    <td class="tg-031e">Kandala / Sikka</td>
                    <td class="tg-031e">1</td>
                    <td class="tg-031e">C</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Goa</td>
                    <td class="tg-031e">Murmagoa</td>
                    <td class="tg-031e">1</td>
                    <td class="tg-031e">D</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mumbai</td>
                    <td class="tg-031e">Mangalore</td>
                    <td class="tg-031e">4</td>
                    <td class="tg-031e">D</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Chennai</td>
                    <td class="tg-031e">Chennai / Ennore</td>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">2</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Tutricorin</td>
                    <td class="tg-031e">3</td>
                    <td class="tg-031e">A</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Vizag</td>
                    <td class="tg-031e">4</td>
                    <td class="tg-031e">C</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Kakinada</td>
                    <td class="tg-031e">Vizag / Kakinada</td>
                    <td class="tg-031e">1</td>
                    <td class="tg-031e">C</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Paradip</td>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">C</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Kolkatta</td>
                    <td class="tg-031e">Kolkatta / Haldia</td>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">B</td>
                  </tr>
                  <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e">Paradip</td>
                    <td class="tg-031e">4</td>
                    <td class="tg-031e">B</td>
                  </tr>
                </table>	
            </div>
        </div>
    
    
		<div id='tab3' class="tab1">
			 <div class="container mt30 mb40">
					<div id='tab2' class="tab1">
			 <div class="container mt30 mb40">
			
                <table class="tg left">
                  <tr>
                    <th class="tg-031e">GRADES</th>
                    <th class="tg-031e" colspan="4">PORT RATINGS</th>
                  </tr>
                  <tr>
                    <th class="tg-031e"></th>
                    <th class="tg-031e">A</th>
                    <th class="tg-031e">B</th>
                    <th class="tg-031e">C</th>
                    <th class="tg-031e">D</th>
                  </tr>
                  <tr>
                    <th class="tg-031e">DIESEL ENGINE LUBRICANT</th>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 570</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 300</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M30Series</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M40 Series</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M50</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 412</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 450 NC</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard ADL Series</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard HSD</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Delvac MX 15W40</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral Engine Oils</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">HYDRAULIC OILS</th>
                    <th class="tg-031e"></th>
                    <td class="tg-031e"></td>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 32</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>

                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 46</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 68</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 100</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 150</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral hydraulic oils</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">GEAR OILS</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 626</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 627</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 629</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 630</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 632</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 634</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 636</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other mineral gear oils </td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <!--<tr>
                    <th class="tg-031e">CIRCULATING OILS</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Light</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Heavy Medium</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Heavy</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral Oil</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Refrigeration Oil</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Gargoyale Artic Oil 300</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Other Mineral Lubricants</td>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Stern Tube Lube</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilarma 798</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobiltherm 603/605, Esso Therm 500</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus 427</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Greases</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilux EP2</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil TAC 375 NC</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgrease XHP 222</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Beacon 3</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Synthetics</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus 827</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus SHC 1026</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Other Synthetics</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>-->
                </table>	
                
                
                
                
                <table class="tg right">
                  <tr>
                    <th class="tg-031e">GRADES</th>
                    <th class="tg-031e" colspan="4">PORT RATINGS</th>
                  </tr>
                  <tr>
                    <th class="tg-031e"></th>
                    <th class="tg-031e">A</th>
                    <th class="tg-031e">B</th>
                    <th class="tg-031e">C</th>
                    <th class="tg-031e">D</th>
                  </tr>
             <!--     <tr>
                    <th class="tg-031e">DIESEL ENGINE LUBRICANT</th>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 570</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 300</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M30Series</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M40 Series</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard M50</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 412</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard 450 NC</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard ADL Series</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgard HSD</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Delvac MX 15W40</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral Engine Oils</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">HYDRAULIC OILS</th>
                    <th class="tg-031e"></th>
                    <td class="tg-031e"></td>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 32</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>

                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 46</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 68</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 100</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Nuto H 150</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral hydraulic oils</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">GEAR OILS</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 626</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 627</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 629</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 630</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 632</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 634</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgear 636</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other mineral gear oils </td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>-->
                    <th class="tg-031e">CIRCULATING OILS</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Light</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Heavy Medium</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil DTE Oil Heavy</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">All other Mineral Oil</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Refrigeration Oil</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Gargoyale Artic Oil 300</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Other Mineral Lubricants</td>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Stern Tube Lube</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilarma 798</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobiltherm 603/605, Esso Therm 500</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus 427</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Greases</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilux EP2</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil TAC 375 NC</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobilgrease XHP 222</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Beacon 3</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <th class="tg-031e">Synthetics</th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                    <th class="tg-031e"></th>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus 827</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Mobil Rarus SHC 1026</td>
                    <td class="tg-031e">Y</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                  <tr>
                    <td class="tg-031e">Other Synthetics</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                    <td class="tg-031e">S</td>
                  </tr>
                </table>	
                
                <div class="left p25 mt20">
                <p class="content"><i class="fa fa-arrow-circle-right"></i><strong style="padding:5px;">A</strong> = Available</p>
                <p class="content"><i class="fa fa-arrow-circle-right"></i><strong style="padding:5px">S</strong> = Subject To Enquiry</p>
                </div>
                
                <div class="left">
                	<p class="content mt15">
                    Products that are subject to inquiry would require 7 working days over and above the normal lead time for Mineral Oils and 90 days for Synthetic Oils.<br /><br />Minimum Order Quantity should be five barrels (1040 Liters or 1040 Kgs)All A Rate Ports have Pumping Facility.<br /><br /> In case of Pumping the lead time would be enhanced by 1 working day.
                    </p>
                </div>
		</div>
        </div>
		</div>
	</div>
    
     <div id='tab4' class="tab1">
		<div class="container mt30 mb40">
				<div class="float">
			<div class="left grid2">
            	<img src="images/india-map.png"  alt="india-map" width="400px" />
            </div>
            <div class=" left grid7">
            	<p class="content p25"> ExxonMobil customers benefit from global product availability and efficiency. Our extensive ports network and our 	  experienced team enables us to deliver the products you need, when and where you need them.<br /><br />

We always Endeavour to optimize our port network. We therefore encourage online search of the International Ports and Services from the link below.
				</p>
                
                <span id="link"><a href="http://www.exxonmobilportsandservices.com/" target="_blank">View International Ports & Services</a></span>
                
                
            </div>
            
            
         </div>	
		</div>
	 </div> 
    
    
      <div id='tab5' class="tab1">
			 <div class="container mt30 mb40">
				<div class="float">
			<div class="left grid2">
            	<img src="images/ANALISI OLIO.JPG"  alt="signum" width="400px" />
            </div>
            <div class=" left grid7">
            	<p class="content2"><span><strong class="arrow">  </strong></span>Signum Oil Analysis can help you increase fleet productivity and decrease maintenance costs.A well-managed oil analysis program can lead to a healthier bottom-line for your company.<br/><br/>
                >> Detect and prevent potential equipment failures.<br/><br/>
				>> Reduce unscheduled downtime.<br/><br/>
				>> Decrease lubricant consumption and disposal.<br/><br/>
                
                
					<span class="signum-link"><a href="http://www.exxonmobil.com/lubes/exxonmobil/marine/signum_demo.html" target="_blank">View Signum Oil Analysis Online Demo</a></span>
				</p>
            </div>
            
            <div class="float mt20">
            	<p class="content">
                	ExxonMobil has enhanced Signum Oil Analysis to offer even more:<br /><br />
                	<strong>Improved Web Site :</strong><br />
new features to help you manage oil analysis results and maintenance activities with greater ease and efficiency.<br /><br />

<strong>Application-specific Tests :</strong><br />
Our laboratory testing regimen is the result of years of experience researching and developing marine lubricants. We match the most appropriate battery of tests to each specific equipment application.<br /><br />

<strong>Superior Alert System :</strong><br />
Robust condition trending that goes beyond single condition alarms from an alert system that also cross-references results from multiple tests.<br /><br />

<strong>Easy-to-Read, More Useful Sample Reports :</strong><br />
Expect to receive timely and accurate information when and how you need it, and expert insights about the condition of your fleet's engines, shipboard equipment and oil.<br /><br />

<strong>Comprehensive Summaries :</strong><br />
Identify trends not typically seen when viewing individual sample reports with summaries that enable you to see the health of your fleet detailed by alarm, equipment type, product in use, application and vessel.<br /><br />

Sophisticated testing, technical expertise, a global database, and useful online features help make Signum the marine industry's most comprehensive oil analysis program.
                </p>
            </div>
         </div>
		     </div>
	  </div> 
    
    
</div>

</div>

</div>
</div>
</div>
</div>


<div class="float dark-green">
<div class="auto2">
<div class="auto">
<div class="float mt35">

<div class="left grid2">
<a href="index.php"><img src="images/mars-logo.png" alt="logo" title="logo" /></a>
<p class="content mt20">Copyright &copy; 2015, <a class="link" href="#">Mars Petrochem Pvt Ltd.</a></p>
<p class="content">All Rights Reserved.</p>
<br />
<p class="content">
<a class="link" href="#">Privacy Policy </a> |  <a class="link" href="#">Disclaimer</a>
</p>
<br />
<ul class="social mb40">
<li><a href="#"><img src="images/facebook.png" alt="facebook" title="facebook"  id="fb" /></a></li>
<li><a href="#"><img src="images/twitter.png" alt="twitter" title="twitter" id="twitter" /></a></li>
<li><a href="#"><img src="images/in.png" alt="in" title="in" id="in" /></a></li>
</ul>
</div>

<div class="left grid2">
<h4><span class="ml25">NAVIGATE</span></h4>
<ul class="naviagte">
<li><a href="index.php">Home</a></li>
<div class="float divider"></div>
<li><a href="about-us.php#about-us">Profile</a></li>
<div class="float divider"></div>
<li class="active2"><a href="industrial-lubricants.php#industrial-lubricants">Products</a></li>
<div class="float divider"></div>
<li><a class="sheet" href="http://www.msds.exxonmobil.com/IntApps/psims/psims.aspx" target="_blank">Material Safety Data Sheet</a></li>
</ul>

<ul class="naviagte">
<li><a href="careers.php#careers">Careers</a></li>
<div class="float divider"></div>
<li><a href="http://www.mobilindustrial.com/ind/english/productselector.aspx" target="_blank">Product Selector</a></li>
<div class="float divider"></div>
<li><a href="gallery.php#gallery">Gallery</a></li>
<div class="float divider"></div>
<li ><a href="contact-us.php#contact-us">Contact</a></li>
</ul>
</div>

<div class="right grid2">
<h4><span class="ml30">CONTACT</span></h4>
<ul class="contact">
<li class="phone-icon"><p class="content ">Call Us At :<br />+91-22-65505615/07/08 </p>
<p  class="content">+91-22-23723836</p></li>
<div class="float divider"></div>
<li class="email-icon"><p class="content">Email Us Here :<br />info@marspetrochem.com</p></li>
</ul>
</div>

</div>
</div>
</div>
</div>
<script>
			// Wait until the DOM has loaded before querying the document
			$(document).ready(function(){
				$('ul.tabs').each(function(){
					// For each set of tabs, we want to keep track of
					// which tab is active and it's associated content
					var $active, $content, $links = $(this).find('a');

					// If the location.hash matches one of the links, use that as the active tab.
					// If no match is found, use the first link as the initial active tab.
					$active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
					$active.addClass('active');

					$content = $($active[0].hash);

					// Hide the remaining content
					$links.not($active).each(function () {
						$(this.hash).hide();
					});

					// Bind the click event handler
					$(this).on('click', 'a', function(e){
						// Make the old tab inactive.
						$active.removeClass('active');
						$content.hide();

						// Update the variables with the new link and content
						$active = $(this);
						$content = $(this.hash);

						// Make the tab active.
						$active.addClass('active');
						$content.show();

						// Prevent the anchor's default click action
						e.preventDefault();
					});
				});
			});
		</script>
        <script>
  $( "#fb" ).hover(
  function() {
    $("#fb").attr('src','images/facebook-hover.png');
  }, function() {
   $("#fb").attr( 'src','images/facebook.png' );
  }
);


  $( "#twitter" ).hover(
  function() {
    $("#twitter").attr('src','images/twitter-hover.png');
  }, function() {
   $("#twitter").attr( 'src','images/twitter.png' );
  }
);


  $( "#in" ).hover(
  function() {
    $("#in").attr('src','images/in-hover.png');
  }, function() {
$("#in").attr( 'src','images/in.png' );
  }
);
</script>
</body>
</html>