<!doctype html>
<!--[if lt IE 7 ]> <html class=ie6> <![endif]-->
<!--[if IE 7 ]> <html class=ie7> <![endif]-->
<!--[if IE 8 ]> <html class=ie8> <![endif]-->
<!--[if IE 9 ]> <html class=ie9> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
<head>
<!--[if lt IE 9]>l
<script src=http://html5shiv.googlecode.com/svn/trunk/html5.js></script>
<![endif]-->
<meta charset="utf-8">
<title>Mars Petrochem Pvt Ltd | Automotive Lubricants</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="rating" content="general" />
<meta name="copyright" content="2014, mars petrochem" />
<meta name="revisit-after" content="7 Days" />
<meta name="expires" content="never" />
<meta name="distribution" content="global" />
<meta name="robots" content="index, follow" />
<!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<meta name="viewport" content="width=1240px">
<link type="text/css" rel="stylesheet" href="css/main.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>


<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
        <script type="text/javascript" src="js/ticker.js"></script>
<!-- End WOWSlider.com HEAD section -->
<link rel="stylesheet" href="css/accordian.css" />
<script type="text/javascript" src="js/accordian.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>

<body>
<div class="float header-bg">
<div class="auto2">
<div class="auto">
<div class="float">

<ul class="menu">
<li ><a href="index.php">HOME</a></li>
<li><a href="about-us.php#about-us">PROFILE</a>
 <ul class="dropmenu">
  <li><a href="about-us.php#about-us">About Us</a></li>
  <li><a href="our-mission.php#our-mission">Our Mission</a></li>
  <li><a href="our-vision.php#our-vision">Our Vision</a></li>
  <li><a href="our-people.php#our-people">Our People</a></li>
  <li><a href="Infrastructure.php#Infrastructure">Infrastructure</a></li>
  </ul>
</li>
<li class="active"><a href="industrial-lubricants.php#industrial-lubricantss">PRODUCT</a>
	<ul class="dropmenu">
      <li><a href="industrial-lubricants.php#industrial-lubricants">Industrial Lubricants</a></li>
      <li><a href="automotive-lubricants.php#automotive-lubricant">Automotive Lubricants</a></li>
      <li><a href="marine-lubricants.php#marine-lubricants">Marine Lubricants</a></li>
  </ul>
</li>
<li><a href="gallery.php#gallery">GALLERY</a></li>
<li><a href="careers.php#careers">CAREERS</a></li>
<li ><a href="contact-us.php#contact-us">CONTACT</a></li>
<li><a href="events.php#events">EVENTS</a></li>
<li><a href="partners.php#partners">PARTNERS</a></li>
</ul>

<div class="right">
<ul class="links">
<li><a href="http://www.mobilindustrial.com/ind/english/productselector.aspx" target="_blank"><img src="images/blue-btn1-bg.png" width="205px" /></a></li>
<li><a href="http://www.msds.exxonmobil.com/IntApps/psims/psims.aspx" target="_blank"><img src="images/blue-btn2-bg.png" width="150px" alt="Material Safety Data Sheet" title="Material Safety Data Sheet" /></a></li>
</ul>
</div>



<div class="float">
<div class="left mt30">
<a href="index.php"><img src="images/logo.png" alt="logo" title="logo" /></a>
</div>
<div class="left mt50 ml40">
<img src="images/mobil-logo.png" alt="mobil" title="mobil" />
</div>

<div class="right mt25 phone">
<h6><img src="images/icon-1.png" alt="phone" title="phone"/>+91-22-65505615/ 07/08 /+91-22-23723836</h6>
<h6><img src="images/icon-2.png" alt="email" title="email" /><a style="color:#333333;" href="mailto:info@marspetrochem.com">info@marspetrochem.com</a></h6>
</div>
</div>


</div>
</div>
</div>
</div>







<div class="float relative">
<div class="absolute">
<img src="images/awards.png" alt="awards" title="awards" />
</div>

<!-- Start WOWSlider.com BODY section id=wowslider-container1 -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/img1.jpg" alt="img1" title="img1" id="wows1_0"/></li>
<li><img src="data1/images/img4.jpg" alt="img4" title="img4" id="wows1_1"/></li>
<li><img src="data1/images/img1.jpg" alt="img1" title="img3" id="wows1_2"/></li>
<li><img src="data1/images/img4.jpg" alt="img4" title="img1" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="img1">1</a>
<a href="#" title="img4">2</a>
<a href="#" title="img1">3</a>
<a href="#" title="img4">4</a>
</div></div>
<!-- Generated by WOWSlider.com v3.4 -->
	<a href="#" class="ws_frame"></a>
	
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
<!-- End WOWSlider.com BODY section -->

</div>

<div class="float">
<div class="auto">
<div class="auto2">
<div class="float">
<ul class="clients">
<li><img src="images/icon-4.png" /></li>
<li><img src="images/client-1.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-2.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-3.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-4.png" /></li>
<div class="ver-divider"></div>
<li><img src="images/client-5.png" /></li>
</ul>
</div>
</div>
</div>
</div>

<div id="automotive-lubricant" class="float dark-green">
<div class="auto2">
<div class="auto">
<div class="float">
<div class="left mt15 mb5">
<img src="images/icon-3.png" alt="news"  title="news" />
</div>
<div class="float mt15 ml30" id="ticker">
<ul>
    <li><h5>Gulf Oil Lubri standalone Sep '14 sales at Rs 243.27 crore</h5>
    <span class="left">5.13 pm | 06 Nov 2014 |  Source: <a href="http://www.moneycontrol.com/">Moneycontrol.com</a></span>

    </li>
    <li><h5>Gulf Oil Lubri standalone Sep '14 sales at Rs 243.27 crore</h5>
    <span class="left">5.13 pm | 06 Nov 2014 |  Source: <a href="http://www.moneycontrol.com/">Moneycontrol.com</a></span>
   
    </li>
 </ul>
<a class="news-btn" href="#">VIEW ALL NEWS</a>
</div>
<script>
$(function() {
  $('#ticker').vTicker();
});
</script>


</div>
</div>
</div>
</div>



<!-- page will come here -->
<div class="float middle-bg ">
<div class="auto2">
<div class="auto">
<div class="float mt30">

<p class="content mb20 font underline"><strong>Automotive Lubricants</strong></p>

<div class="float mb40">
<div class="grid2 left">
<img src="images/mobil-car.jpg" alt="industrial-lubricant" width="375px" height="240px"/>
</div>
<div class="right" style="width:800px">
<p class="content mb5 ml10">
<strong>Nothing works harder to keep your car, truck, van or SUV running smoothly than Mobil oils.</strong><br /><br />

<strong>From conventional to fully synthetic, high-performance to high-mileage, Mobil has the type of oil you need to go the distance time & again.</strong> <br />
</p>
</div>
</div>








</div>
</div>
</div>
</div>


<div class="float dark-green">
<div class="auto2">
<div class="auto">
<div class="float mt35">

<div class="left grid2">
<a href="index.php"><img src="images/mars-logo.png" alt="logo" title="logo" /></a>
<p class="content mt20">Copyright &copy; 2015, <a class="link" href="#">Mars Petrochem Pvt Ltd.</a></p>
<p class="content">All Rights Reserved.</p>
<br />
<p class="content">
<a class="link" href="#">Privacy Policy </a> |  <a class="link" href="#">Disclaimer</a>
</p>
<br />
<ul class="social mb40">
<li><a href="#"><img src="images/facebook.png" alt="facebook" title="facebook"  id="fb" /></a></li>
<li><a href="#"><img src="images/twitter.png" alt="twitter" title="twitter" id="twitter" /></a></li>
<li><a href="#"><img src="images/in.png" alt="in" title="in" id="in" /></a></li>
</ul>
</div>

<div class="left grid2">
<h4><span class="ml25">NAVIGATE</span></h4>
<ul class="naviagte">
<li><a href="index.php">Home</a></li>
<div class="float divider"></div>
<li class="active2"><a href="about-us.php#about-us">Profile</a></li>
<div class="float divider"></div>
<li><a href="#">Products</a></li>
<div class="float divider"></div>
<li><a class="sheet" href="#">Material Safety Data Sheet</a></li>
</ul>

<ul class="naviagte">
<li><a href="careers.php#careers">Careers</a></li>
<div class="float divider"></div>
<li><a href="#">Product Selector</a></li>
<div class="float divider"></div>
<li><a href="#">Gallery</a></li>
<div class="float divider"></div>
<li ><a href="contact-us.php#contact-us">Contact</a></li>
</ul>
</div>

<div class="right grid2">
<h4><span class="ml30">CONTACT</span></h4>
<ul class="contact">
<li class="phone-icon"><p class="content ">Call Us At :<br />+91-22-65505615/ 07/08 </p>
<p  class="content">+91-22-23723836</p></li>
<div class="float divider"></div>
<li class="email-icon"><p class="content">Email Us Here :<br />info@marspetrochem.com</p></li>
</ul>
</div>

</div>
</div>
</div>
</div>
<script>
  $( "#fb" ).hover(
  function() {
    $("#fb").attr('src','images/facebook-hover.png');
  }, function() {
   $("#fb").attr( 'src','images/facebook.png' );
  }
);


  $( "#twitter" ).hover(
  function() {
    $("#twitter").attr('src','images/twitter-hover.png');
  }, function() {
   $("#twitter").attr( 'src','images/twitter.png' );
  }
);


  $( "#in" ).hover(
  function() {
    $("#in").attr('src','images/in-hover.png');
  }, function() {
$("#in").attr( 'src','images/in.png' );
  }
);
</script>
</body>
</html>